// SPDX-License-Identifier: GPL-3.0-or-later
import { hz, mW } from '../../model/units.js'
import { CTCSS_DECIHZ, DTCS_CODES } from '../../model/tones.js'
import type { RadioSchema } from '../../radio/schema.js'
import {
  DM32_COLOURS,
  DM32_KEY_FUNCTIONS,
  KEY_SLOTS,
  MESSAGE_MAX_CHARS,
  MESSAGE_SLOTS,
  SCANLIST_MAX_MEMBERS,
} from './layout.js'
import { BAUD_RATE, OPEN_SETTLE_MS } from './protocol.js'

const COLOUR_OPTIONS = DM32_COLOURS.map((label, value) => ({ value, label }))
const KEY_OPTIONS = DM32_KEY_FUNCTIONS.map((label, value) => ({ value, label }))
const ON_OFF = [
  { value: 0, label: 'Off' },
  { value: 1, label: 'On' },
]

/**
 * The settings this build is prepared to change.
 *
 * Deliberately a subset. Block 0x04 is 4 KiB and the reference names perhaps a
 * tenth of it with confidence; the rest is decoded where it can be, round-tripped
 * everywhere, and offered nowhere. A control for a byte whose meaning is a guess
 * is worse than no control, because the user cannot tell the difference.
 */
export const DM32UV_SETTINGS_GROUPS = [
  {
    id: 'display',
    label: 'Display',
    description: 'What the radio shows when it powers on and how it is lit.',
    fields: [
      {
        key: 'powerOnInterface',
        label: 'Power-on screen',
        type: 'enum',
        options: [
          { value: 0, label: 'Picture' },
          { value: 1, label: 'Custom message' },
          { value: 2, label: 'Battery voltage' },
        ],
        icon: 'lucide:monitor',
      },
      { key: 'powerOnLine1', label: 'Power-on line 1', type: 'string', maxLength: 13 },
      { key: 'powerOnLine2', label: 'Power-on line 2', type: 'string', maxLength: 13 },
      {
        key: 'backlightBrightness',
        label: 'Backlight brightness',
        help: 'Stored 0-5; the radio shows it as 1-6.',
        type: 'int',
        min: 0,
        max: 5,
      },
      { key: 'autoBacklightDuration', label: 'Backlight timeout', type: 'int', min: 0, max: 5, help: '0 is 5 seconds, each step adds 5.' },
      { key: 'displayFlags.volumeChangePrompt', label: 'Show volume changes', type: 'bool' },
      { key: 'displayFlags.timeDisplay', label: 'Show the clock', type: 'bool' },
      {
        key: 'displayFlags.dateFormat',
        label: 'Date format',
        type: 'enum',
        options: [
          { value: 0, label: 'Year / month / day' },
          { value: 1, label: 'Day / month / year' },
        ],
      },
      { key: 'menuExitTime', label: 'Menu timeout', type: 'int', min: 0, max: 30, help: 'Seconds. 0 on both radios seen so far, which the reference does not explain.' },
    ],
  },
  {
    id: 'tones',
    label: 'Alert tones',
    description:
      'Which events the radio beeps for. The bit positions come from the reference implementation’s own ' +
      'interface rather than from a capture, so they are its reading rather than an attested one.',
    fields: [
      { key: 'alertTones.keyPress', label: 'Key press', type: 'bool', icon: 'lucide:volume-2' },
      { key: 'alertTones.keyRelease', label: 'Key release', type: 'bool' },
      { key: 'alertTones.menuExit', label: 'Leaving a menu', type: 'bool' },
      { key: 'alertTones.callEnd', label: 'End of call', type: 'bool' },
      { key: 'alertTones.talkPermit', label: 'Talk permit', type: 'bool' },
      { key: 'alertTones.startUpSound', label: 'Power on', type: 'bool' },
      { key: 'alertTones.voicePrompt', label: 'Voice prompt', type: 'bool' },
      { key: 'alertTones.scanStop', label: 'Scan stops', type: 'bool' },
      { key: 'alertTonesCont.batteryLow', label: 'Battery low', type: 'bool' },
      { key: 'alertTonesCont.analogTxEnd', label: 'Analog transmit ends', type: 'bool' },
      { key: 'alertTonesCont.analogTxAlert', label: 'Analog transmit alert', type: 'bool' },
    ],
  },
  {
    id: 'colours',
    label: 'Colours',
    description: 'The six display colours the radio stores, one nibble each.',
    fields: [
      { key: 'callsignColour.colour', label: 'Callsign', type: 'enum', options: COLOUR_OPTIONS },
      { key: 'standbyTextColour.colour', label: 'Standby text', type: 'enum', options: COLOUR_OPTIONS },
      { key: 'channelAColour.colour', label: 'Channel A', type: 'enum', options: COLOUR_OPTIONS },
      { key: 'channelBColour.colour', label: 'Channel B', type: 'enum', options: COLOUR_OPTIONS },
      { key: 'zoneAColour.colour', label: 'Zone A', type: 'enum', options: COLOUR_OPTIONS },
      { key: 'zoneBColour.colour', label: 'Zone B', type: 'enum', options: COLOUR_OPTIONS },
      {
        key: 'standbyCharColour1',
        label: 'Standby character',
        help: 'A whole byte rather than a nibble, and its range runs to 30 rather than the colour list. The reference has no second offset for the pair this belongs to.',
        type: 'int',
        min: 0,
        max: 30,
      },
    ],
  },
  {
    id: 'keys',
    label: 'Keys',
    description: 'What the side and programmable keys do. The radio offers the same list for every one.',
    fields: [
      { key: 'sk1Short', label: 'SK1 short press', type: 'enum', options: KEY_OPTIONS, icon: 'lucide:square-mouse-pointer' },
      { key: 'sk1Long', label: 'SK1 long press', type: 'enum', options: KEY_OPTIONS },
      { key: 'sk2Short', label: 'SK2 short press', type: 'enum', options: KEY_OPTIONS },
      { key: 'sk2Long', label: 'SK2 long press', type: 'enum', options: KEY_OPTIONS },
      { key: 'p1Short', label: 'P1 short press', type: 'enum', options: KEY_OPTIONS },
      { key: 'p1Long', label: 'P1 long press', type: 'enum', options: KEY_OPTIONS },
      { key: 'p2Short', label: 'P2 short press', type: 'enum', options: KEY_OPTIONS },
      { key: 'p2Long', label: 'P2 long press', type: 'enum', options: KEY_OPTIONS },
      { key: 'longPressTime', label: 'Long press time', type: 'int', min: 0, max: 4, help: 'Stored 0-4; the radio shows it as 1-5.' },
      { key: 'keyLockFlags.lockKey', label: 'Keypad lock', type: 'enum', options: [{ value: 0, label: 'Manual' }, { value: 1, label: 'Automatic' }] },
      { key: 'keyLockFlags.knobLock', label: 'Lock the knob', type: 'bool' },
      { key: 'keyLockFlags.sideKeyLock', label: 'Lock the side keys', type: 'bool' },
      { key: 'autoKeypadLockDelay', label: 'Auto lock after', type: 'int', min: 0, max: 60, help: 'Seconds.' },
    ],
  },
  {
    id: 'dmr',
    label: 'DMR',
    fields: [
      { key: 'digitalDecodeFlags.privateCallMatch', label: 'Match private calls', type: 'bool' },
      { key: 'digitalDecodeFlags.groupCallMatch', label: 'Match group calls', type: 'bool' },
      { key: 'callHoldTime', label: 'Call hold time', type: 'int', min: 0, max: 61, help: 'Seconds.' },
      { key: 'activeRetriesTime', label: 'Active retries', type: 'int', min: 1, max: 8 },
      {
        key: 'activeWaitTime',
        label: 'Active wait time',
        help: 'Raw. The reference gives (raw-1)x30+300 ms but derives it from a comment rather than a capture, so the byte is shown as the byte.',
        type: 'int',
        min: 0,
        max: 255,
      },
      { key: 'preCarrierTime', label: 'Pre-carrier time', help: 'Raw, for the same reason.', type: 'int', min: 0, max: 255 },
      { key: 'smsFormat', label: 'SMS format', help: 'Raw, for the same reason.', type: 'int', min: 0, max: 255 },
      { key: 'txDwellTime', label: 'Transmit dwell time', type: 'int', min: 0, max: 255 },
      { key: 'digitalFlags.missedCallAlert', label: 'Alert on a missed call', type: 'bool' },
      { key: 'digitalFlags.callAlertDecode', label: 'Decode call alert', type: 'bool' },
      { key: 'digitalFlags.radioEnableDecode', label: 'Decode radio enable', type: 'bool' },
      { key: 'digitalFlags.radioCheckDecode', label: 'Decode radio check', type: 'bool' },
      { key: 'digitalFlags.radioDisableDecode', label: 'Decode radio disable', type: 'bool' },
      { key: 'digitalFlags.remoteMonitorDecode', label: 'Decode remote monitor', type: 'bool' },
      { key: 'nameDisplayFlags.sendTxName', label: 'Send the radio name when transmitting', type: 'bool' },
      { key: 'nameDisplayFlags.nameDisplayPriority', label: 'Prefer the name over the number', type: 'bool' },
    ],
  },
  {
    id: 'gps',
    label: 'GPS',
    description: 'This radio has a receiver; the position below is where it last had a fix or was told it was.',
    fields: [
      { key: 'gpsFlags.gpsSwitch', label: 'GPS', type: 'enum', options: ON_OFF, icon: 'lucide:satellite' },
      {
        key: 'gpsFlags.gpsMode',
        label: 'Constellation',
        type: 'enum',
        options: [
          { value: 0, label: 'GPS' },
          { value: 1, label: 'BeiDou' },
          { value: 2, label: 'GPS + BeiDou' },
        ],
      },
      { key: 'gpsFlags.distanceUnit', label: 'Distance', type: 'enum', options: [{ value: 0, label: 'Metric' }, { value: 1, label: 'Imperial' }] },
      {
        key: 'gpsFlags.speedUnit',
        label: 'Speed',
        type: 'enum',
        options: [
          { value: 0, label: 'km/h' },
          { value: 1, label: 'mph' },
          { value: 2, label: 'knots' },
        ],
      },
      { key: 'gpsFlags.gpsDisplayFormat', label: 'Position format', type: 'enum', options: [{ value: 0, label: 'Degrees' }, { value: 1, label: 'Degrees, minutes, seconds' }] },
      { key: 'gpsReportInterval', label: 'Report interval', type: 'int', min: 5, max: 255, help: 'Seconds.' },
      {
        key: 'utcZone',
        label: 'Time zone',
        type: 'enum',
        options: Array.from({ length: 26 }, (_, i) => ({
          value: i,
          label: i === 12 ? 'UTC' : `UTC${i < 12 ? '-' : '+'}${Math.abs(i - 12)}`,
        })),
      },
    ],
  },
  {
    id: 'power',
    label: 'Power',
    fields: [
      { key: 'allowReset.allowReset', label: 'Allow reset from the keypad', type: 'bool' },
      {
        key: 'autoPowerOff',
        label: 'Automatic power off',
        type: 'enum',
        options: [
          { value: 0, label: 'Off' },
          { value: 1, label: '30 minutes' },
          { value: 2, label: '60 minutes' },
          { value: 3, label: '120 minutes' },
          { value: 4, label: '240 minutes' },
          { value: 5, label: '480 minutes' },
        ],
        icon: 'lucide:power',
      },
    ],
  },
  {
    id: 'onetouch',
    label: 'One-touch calls',
    description:
      'The five calls the radio can place from a single key. All five entries in the capture decode ' +
      'inside their own enums, which is what settled the layout.',
    fields: [
      { key: 'oneTouch1Type', label: 'Call 1 mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'oneTouch1Object', label: 'Call 1 target', type: 'int', min: 0, max: 65535 },
      { key: 'oneTouch1CallType', label: 'Call 1 type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'oneTouch1Sms', label: 'Call 1 message', type: 'int', min: 0, max: 255 },
      { key: 'oneTouch2Type', label: 'Call 2 mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'oneTouch2Object', label: 'Call 2 target', type: 'int', min: 0, max: 65535 },
      { key: 'oneTouch2CallType', label: 'Call 2 type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'oneTouch2Sms', label: 'Call 2 message', type: 'int', min: 0, max: 255 },
      { key: 'oneTouch3Type', label: 'Call 3 mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'oneTouch3Object', label: 'Call 3 target', type: 'int', min: 0, max: 65535 },
      { key: 'oneTouch3CallType', label: 'Call 3 type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'oneTouch3Sms', label: 'Call 3 message', type: 'int', min: 0, max: 255 },
      { key: 'oneTouch4Type', label: 'Call 4 mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'oneTouch4Object', label: 'Call 4 target', type: 'int', min: 0, max: 65535 },
      { key: 'oneTouch4CallType', label: 'Call 4 type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'oneTouch4Sms', label: 'Call 4 message', type: 'int', min: 0, max: 255 },
      { key: 'oneTouch5Type', label: 'Call 5 mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'oneTouch5Object', label: 'Call 5 target', type: 'int', min: 0, max: 65535 },
      { key: 'oneTouch5CallType', label: 'Call 5 type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'oneTouch5Sms', label: 'Call 5 message', type: 'int', min: 0, max: 255 },
    ],
  },
  {
    id: 'funplus',
    label: 'Fun+',
    description:
      'Ten shortcuts reached through the Fun+ key. Each is either a call or a jump into a menu; the ' +
      'number is the position in this list and is not stored with the entry.',
    fields: [
      { key: 'funPlus1Mode', label: 'Fun+ 1 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus1Menu', label: 'Fun+ 1 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus1CallWay', label: 'Fun+ 1 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus1CallObject', label: 'Fun+ 1 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus1CallType', label: 'Fun+ 1 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus1Sms', label: 'Fun+ 1 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus2Mode', label: 'Fun+ 2 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus2Menu', label: 'Fun+ 2 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus2CallWay', label: 'Fun+ 2 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus2CallObject', label: 'Fun+ 2 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus2CallType', label: 'Fun+ 2 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus2Sms', label: 'Fun+ 2 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus3Mode', label: 'Fun+ 3 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus3Menu', label: 'Fun+ 3 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus3CallWay', label: 'Fun+ 3 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus3CallObject', label: 'Fun+ 3 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus3CallType', label: 'Fun+ 3 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus3Sms', label: 'Fun+ 3 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus4Mode', label: 'Fun+ 4 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus4Menu', label: 'Fun+ 4 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus4CallWay', label: 'Fun+ 4 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus4CallObject', label: 'Fun+ 4 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus4CallType', label: 'Fun+ 4 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus4Sms', label: 'Fun+ 4 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus5Mode', label: 'Fun+ 5 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus5Menu', label: 'Fun+ 5 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus5CallWay', label: 'Fun+ 5 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus5CallObject', label: 'Fun+ 5 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus5CallType', label: 'Fun+ 5 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus5Sms', label: 'Fun+ 5 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus6Mode', label: 'Fun+ 6 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus6Menu', label: 'Fun+ 6 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus6CallWay', label: 'Fun+ 6 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus6CallObject', label: 'Fun+ 6 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus6CallType', label: 'Fun+ 6 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus6Sms', label: 'Fun+ 6 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus7Mode', label: 'Fun+ 7 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus7Menu', label: 'Fun+ 7 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus7CallWay', label: 'Fun+ 7 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus7CallObject', label: 'Fun+ 7 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus7CallType', label: 'Fun+ 7 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus7Sms', label: 'Fun+ 7 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus8Mode', label: 'Fun+ 8 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus8Menu', label: 'Fun+ 8 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus8CallWay', label: 'Fun+ 8 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus8CallObject', label: 'Fun+ 8 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus8CallType', label: 'Fun+ 8 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus8Sms', label: 'Fun+ 8 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus9Mode', label: 'Fun+ 9 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus9Menu', label: 'Fun+ 9 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus9CallWay', label: 'Fun+ 9 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus9CallObject', label: 'Fun+ 9 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus9CallType', label: 'Fun+ 9 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus9Sms', label: 'Fun+ 9 message', type: 'int', min: 0, max: 255 },
      { key: 'funPlus10Mode', label: 'Fun+ 10 does', type: 'enum', options: [{ value: 0, label: 'Place a call' }, { value: 1, label: 'Open a menu' }] },
      { key: 'funPlus10Menu', label: 'Fun+ 10 menu', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'SMS' },
          { value: 2, label: 'New SMS' },
          { value: 3, label: 'Shortcut text' },
          { value: 4, label: 'Inbox' },
          { value: 5, label: 'Outbox' },
          { value: 6, label: 'Contact list' },
          { value: 7, label: 'Manual dial' },
          { value: 8, label: 'Call log' },
          { value: 9, label: 'Sent calls' },
          { value: 10, label: 'Answered calls' },
          { value: 11, label: 'Missed calls' },
          { value: 12, label: 'Zone' },
          { value: 13, label: 'Radio settings' },
        ] },
      { key: 'funPlus10CallWay', label: 'Fun+ 10 call mode', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Analog' },
          { value: 2, label: 'Digital' },
        ] },
      { key: 'funPlus10CallObject', label: 'Fun+ 10 target', type: 'int', min: 0, max: 255 },
      { key: 'funPlus10CallType', label: 'Fun+ 10 call type', type: 'enum', options: [
          { value: 0, label: 'Off' },
          { value: 1, label: 'Private' },
          { value: 2, label: 'Group' },
          { value: 3, label: 'Message' },
          { value: 4, label: 'Call alert' },
          { value: 5, label: 'Radio check' },
          { value: 6, label: 'Remote monitor' },
          { value: 7, label: 'Active' },
          { value: 8, label: 'Kill' },
        ] },
      { key: 'funPlus10Sms', label: 'Fun+ 10 message', type: 'int', min: 0, max: 255 },
    ],
  },
  {
    id: 'aprs',
    label: 'APRS',
    description:
      'Position reporting. The latitude and longitude below are the fixed position the radio falls back ' +
      'on, and are the only part of this group a capture confirms outright.',
    fields: [
      { key: 'aprsFixedBeacon.enabled', label: 'Fixed beacon', type: 'bool', icon: 'lucide:radio-tower' },
      { key: 'aprsScheduledSendTime', label: 'Send every', type: 'int', min: 0, max: 240, help: '0 is off; each step is 30 seconds.' },
      { key: 'latitude', label: 'Latitude', type: 'string', maxLength: 9, help: 'Nine characters exactly, e.g. 23.000000.' },
      { key: 'latitudeDirection', label: 'North or south', type: 'string', maxLength: 1 },
      { key: 'longitude', label: 'Longitude', type: 'string', maxLength: 9, help: 'Nine characters exactly, e.g. 118.00000.' },
      { key: 'longitudeDirection', label: 'East or west', type: 'string', maxLength: 1 },
      {
        key: 'aprsUploadId',
        label: 'Upload ID',
        type: 'int',
        min: 0,
        max: 16_777_215,
        help: 'Stored little-endian. Both captured values are only plausible DMR IDs read that way, which is evidence rather than proof.',
      },
      { key: 'aprsCallType.group', label: 'Call type', type: 'enum', options: [{ value: 0, label: 'Private' }, { value: 1, label: 'Group' }] },
      { key: 'aprsRepeaterActiveDelay', label: 'Repeater active delay', type: 'int', min: 0, max: 10, help: '0 is off; each step is 100 ms.' },
      { key: 'aprsReportChannel1', label: 'Report channel 1', type: 'int', min: 0, max: 4000, channelRef: true, help: '0 means whichever channel the radio is on.' },
      { key: 'aprsReportChannel2', label: 'Report channel 2', type: 'int', min: 0, max: 4000, channelRef: true, help: '0 means whichever channel the radio is on.' },
      { key: 'aprsReportChannel3', label: 'Report channel 3', type: 'int', min: 0, max: 4000, channelRef: true, help: '0 means whichever channel the radio is on.' },
      { key: 'aprsReportChannel4', label: 'Report channel 4', type: 'int', min: 0, max: 4000, channelRef: true, help: '0 means whichever channel the radio is on.' },
      { key: 'aprsReportChannel5', label: 'Report channel 5', type: 'int', min: 0, max: 4000, channelRef: true, help: '0 means whichever channel the radio is on.' },
      { key: 'aprsReportChannel6', label: 'Report channel 6', type: 'int', min: 0, max: 4000, channelRef: true, help: '0 means whichever channel the radio is on.' },
      { key: 'aprsReportChannel7', label: 'Report channel 7', type: 'int', min: 0, max: 4000, channelRef: true, help: '0 means whichever channel the radio is on.' },
      { key: 'aprsReportChannel8', label: 'Report channel 8', type: 'int', min: 0, max: 4000, channelRef: true, help: '0 means whichever channel the radio is on.' },
    ],
  },
  {
    id: 'menus',
    label: 'Menu items',
    description:
      'Which entries the radio\u2019s own menus offer. A set bit shows the item - that reading is the ' +
      'reference\u2019s and no capture pins it, so if these come back inverted on a radio, this is why.',
    fields: [
      { key: 'menuZone.zoneList', label: 'Zone list', type: 'bool', icon: 'lucide:list' },
      { key: 'menuZone.newZone', label: 'New zone', type: 'bool' },
      { key: 'menuCall.callAlert', label: 'Call alert', type: 'bool' },
      { key: 'menuCall.radioCheck', label: 'Radio check', type: 'bool' },
      { key: 'menuCall.remoteMonitor', label: 'Remote monitor', type: 'bool' },
      { key: 'menuCall.radioEnable', label: 'Radio enable', type: 'bool' },
      { key: 'menuCall.radioDisable', label: 'Radio disable', type: 'bool' },
      { key: 'menuCall.measurePeriod', label: 'Measure period', type: 'bool' },
      { key: 'menuSettingsA.talkaround', label: 'Talkaround', type: 'bool' },
      { key: 'menuSettingsA.alertTone', label: 'Alert tone', type: 'bool' },
      { key: 'menuSettingsA.txPower', label: 'Transmit power', type: 'bool' },
      { key: 'menuSettingsA.startDisplay', label: 'Start-up display', type: 'bool' },
      { key: 'menuSettingsA.langSelect', label: 'Language', type: 'bool' },
      { key: 'menuSettingsA.matchPrivate', label: 'Match private calls', type: 'bool' },
      { key: 'menuSettingsA.matchGroup', label: 'Match group calls', type: 'bool' },
      { key: 'menuSettingsA.displayMode', label: 'Display mode', type: 'bool' },
      { key: 'menuSettingsB.smsFormat', label: 'SMS format', type: 'bool' },
      { key: 'menuSettingsB.subChannelMode', label: 'Sub-channel mode', type: 'bool' },
      { key: 'menuSettingsB.powerSave', label: 'Power save', type: 'bool' },
      { key: 'menuSettingsB.fmRadio', label: 'FM radio', type: 'bool' },
      { key: 'menuSettingsB.gps', label: 'GPS', type: 'bool' },
      { key: 'menuSettingsB.aprs', label: 'APRS', type: 'bool' },
      { key: 'menuSettingsB.record', label: 'Record', type: 'bool' },
      { key: 'menuContact.addContact', label: 'Add a contact', type: 'bool' },
      { key: 'menuContact.delContact', label: 'Delete a contact', type: 'bool' },
      { key: 'menuContact.editContact', label: 'Edit a contact', type: 'bool' },
      { key: 'menuContact.sendMessage', label: 'Send a message', type: 'bool' },
      { key: 'menuContact.functionality', label: 'Functionality', type: 'bool' },
      { key: 'menuContact.manualDial', label: 'Manual dial', type: 'bool' },
      { key: 'menuContact.csvContacts', label: 'CSV contacts', type: 'bool' },
      { key: 'menuLog.missedCall', label: 'Missed calls', type: 'bool' },
      { key: 'menuLog.answeredCall', label: 'Answered calls', type: 'bool' },
      { key: 'menuLog.sentCall', label: 'Sent calls', type: 'bool' },
      { key: 'menuLog.delLog', label: 'Delete the log', type: 'bool' },
      { key: 'menuChannelA.rxFrequency', label: 'Receive frequency', type: 'bool' },
      { key: 'menuChannelA.txFrequency', label: 'Transmit frequency', type: 'bool' },
      { key: 'menuChannelA.ctcDcs', label: 'CTCSS and DCS', type: 'bool' },
      { key: 'menuChannelA.txContact', label: 'Transmit contact', type: 'bool' },
      { key: 'menuChannelA.colorCode', label: 'Colour code', type: 'bool' },
      { key: 'menuChannelA.timeSlot', label: 'Time slot', type: 'bool' },
      { key: 'menuChannelA.radioId', label: 'Radio ID', type: 'bool' },
      { key: 'menuChannelA.radioName', label: 'Radio name', type: 'bool' },
      { key: 'menuChannelB.channelType', label: 'Channel type', type: 'bool' },
      { key: 'menuChannelB.tdmaDirectMode', label: 'TDMA direct mode', type: 'bool' },
      { key: 'menuChannelB.rxGroupList', label: 'RX group list', type: 'bool' },
      { key: 'menuChannelB.addChannel', label: 'Add a channel', type: 'bool' },
      { key: 'menuChannelB.channelName', label: 'Channel name', type: 'bool' },
    ],
  },
] as const satisfies RadioSchema['settings']

export const DM32UV_SCHEMA: RadioSchema = {
  id: 'dm32uv',
  vendor: 'Baofeng',
  model: 'DM-32UV',
  aliases: ['DP570UV'],
  status: 'read-only',

  capabilities: { read: true, write: false, transports: ['serial'] },

  memory: {
    // The reference implementation's ceiling; the largest codeplug actually
    // attested is far smaller, and the test radio holds 45 channels.
    channelCount: 4000,
    firstIndex: 1,
    specialChannels: [],
    nameLength: 16,
    nameCharset:
      ' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~',
    eraseFill: 0xff,
  },

  rf: {
    bands: [
      { loHz: hz(136_000_000), hiHz: hz(174_000_000), label: '136-174 MHz', txAllowed: true },
      { loHz: hz(400_000_000), hiHz: hz(480_000_000), label: '400-480 MHz', txAllowed: true },
    ],
    modulations: ['FM', 'DMR'],
    bandwidths: [25_000, 12_500],
    // Three levels, not two: byte 0x18 bits 2-1 carry 0=Low, 1=Medium, 2=High.
    // `raw` is the value those two bits hold.
    powerLevels: [
      { id: 'low', label: 'Low', mW: mW(1000), raw: 0 },
      { id: 'medium', label: 'Medium', mW: mW(2500), raw: 1 },
      { id: 'high', label: 'High', mW: mW(5000), raw: 2 },
    ],
    tuningSteps: [2_500, 5_000, 6_250, 10_000, 12_500, 25_000].map((s) => hz(s)),
    duplexes: ['simplex', 'plus', 'minus', 'split', 'off'],
    toneModes: ['none', 'tone', 'tsql', 'dtcs', 'cross'],
    ctcssDeciHz: CTCSS_DECIHZ,
    dtcsCodes: DTCS_CODES,
    canSkip: true,
    hasRxDtcs: true,
    hasCtone: true,
    /** A dedicated per-channel bit, unlike either of the analog radios here. */
    txInhibit: { mechanism: 'Per-channel transmit-forbid flag' },
  },

  features: {
    dmr: { colorCodes: [0, 15], timeslots: 2 },
    zones: { max: 250, channelsPer: 64, nameLength: 11 },
    talkGroups: { max: 800, nameLength: 16 },
    contacts: { max: 50_000 },
    rxGroups: { max: 32 },
    /*
     * Sixteen members, not fifteen.
     *
     * This said 15, which is reading B of the two the layout weighs up - the
     * one the protocol notes reject, because this radio's own first scan list
     * carries a count of 16 and fifteen slots cannot hold sixteen members. The
     * struct, the decoder and the encoder all had 16 (`SCANLIST_MAX_MEMBERS`);
     * only the schema was left behind when that was settled, and nothing read
     * it, so nothing noticed. `validateReferences` reads it, and reported the
     * factory scan list as one entry over capacity - which is what found this.
     * See "Scan list membership - settled 2026-08-20" in the protocol notes.
     */
    scanLists: { max: 32, channelsPer: SCANLIST_MAX_MEMBERS },
    radioIds: { max: 250 },
    messages: { max: MESSAGE_SLOTS, maxChars: MESSAGE_MAX_CHARS },
    encryption: { slots: KEY_SLOTS, types: ['none', 'custom', 'arc4', 'aes128', 'aes256'], nameLength: 10 },
  },

  extraFields: [
    { key: 'colorCode', label: 'Colour code', type: 'int', min: 0, max: 15, icon: 'lucide:hash' },
    {
      key: 'timeSlot',
      label: 'Time slot',
      type: 'enum',
      options: [
        { value: 1, label: '1' },
        { value: 2, label: '2' },
      ],
      icon: 'lucide:layers',
    },
    { key: 'encryptionKeyId', label: 'Encryption key', type: 'int', min: 0, max: KEY_SLOTS, icon: 'lucide:key' },
  ],

  settings: DM32UV_SETTINGS_GROUPS,
}

export const DM32UV_SERIAL = {
  baudRate: BAUD_RATE,
  dataBits: 8,
  stopBits: 1,
  parity: 'none',
  flowControl: 'none',
  signals: { dataTerminalReady: false, requestToSend: false },
  openSettleMs: OPEN_SETTLE_MS,
} as const
